

jobs:
- job: Build_Docker_Images
  pool:
    vmImage: ubuntu-latest
  strategy:
    maxParallel: 10
    matrix:

      ubuntu2204_7.0.2:
        MAJOR_VERSION: 7
        VERSION:  7.0
        LONG_VERSION: 7.0.2
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      alpine313_7.0.2:
        MAJOR_VERSION: 7
        VERSION:  7.0
        LONG_VERSION: 7.0.2
        VARIANT:  alpine313
        PARENT: alpine
        ISPARENT:  True


      scratch313_7.0.2:
        MAJOR_VERSION: 7
        VERSION:  7.0
        LONG_VERSION: 7.0.2
        VARIANT:  scratch313
        PARENT: scratch
        ISPARENT:  True


      vaapi2204_7.0.2:
        MAJOR_VERSION: 7
        VERSION:  7.0
        LONG_VERSION: 7.0.2
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_7.0.2:
        MAJOR_VERSION: 7
        VERSION:  7.0
        LONG_VERSION: 7.0.2
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_6.1.2:
        MAJOR_VERSION: 6
        VERSION:  6.1
        LONG_VERSION: 6.1.2
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      vaapi2204_6.1.2:
        MAJOR_VERSION: 6
        VERSION:  6.1
        LONG_VERSION: 6.1.2
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_6.1.2:
        MAJOR_VERSION: 6
        VERSION:  6.1
        LONG_VERSION: 6.1.2
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_5.1.6:
        MAJOR_VERSION: 5
        VERSION:  5.1
        LONG_VERSION: 5.1.6
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      alpine313_5.1.6:
        MAJOR_VERSION: 5
        VERSION:  5.1
        LONG_VERSION: 5.1.6
        VARIANT:  alpine313
        PARENT: alpine
        ISPARENT:  True


      vaapi2204_5.1.6:
        MAJOR_VERSION: 5
        VERSION:  5.1
        LONG_VERSION: 5.1.6
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_5.1.6:
        MAJOR_VERSION: 5
        VERSION:  5.1
        LONG_VERSION: 5.1.6
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_4.4.5:
        MAJOR_VERSION: 4
        VERSION:  4.4
        LONG_VERSION: 4.4.5
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      alpine313_4.4.5:
        MAJOR_VERSION: 4
        VERSION:  4.4
        LONG_VERSION: 4.4.5
        VARIANT:  alpine313
        PARENT: alpine
        ISPARENT:  True


      scratch313_4.4.5:
        MAJOR_VERSION: 4
        VERSION:  4.4
        LONG_VERSION: 4.4.5
        VARIANT:  scratch313
        PARENT: scratch
        ISPARENT:  True


      vaapi2204_4.4.5:
        MAJOR_VERSION: 4
        VERSION:  4.4
        LONG_VERSION: 4.4.5
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_4.4.5:
        MAJOR_VERSION: 4
        VERSION:  4.4
        LONG_VERSION: 4.4.5
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_4.3.8:
        MAJOR_VERSION: 4
        VERSION:  4.3
        LONG_VERSION: 4.3.8
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      vaapi2204_4.3.8:
        MAJOR_VERSION: 4
        VERSION:  4.3
        LONG_VERSION: 4.3.8
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_4.3.8:
        MAJOR_VERSION: 4
        VERSION:  4.3
        LONG_VERSION: 4.3.8
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_4.2.10:
        MAJOR_VERSION: 4
        VERSION:  4.2
        LONG_VERSION: 4.2.10
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      scratch313_4.2.10:
        MAJOR_VERSION: 4
        VERSION:  4.2
        LONG_VERSION: 4.2.10
        VARIANT:  scratch313
        PARENT: scratch
        ISPARENT:  True


      vaapi2204_4.2.10:
        MAJOR_VERSION: 4
        VERSION:  4.2
        LONG_VERSION: 4.2.10
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_4.2.10:
        MAJOR_VERSION: 4
        VERSION:  4.2
        LONG_VERSION: 4.2.10
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_3.4.13:
        MAJOR_VERSION: 3
        VERSION:  3.4
        LONG_VERSION: 3.4.13
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      alpine313_3.4.13:
        MAJOR_VERSION: 3
        VERSION:  3.4
        LONG_VERSION: 3.4.13
        VARIANT:  alpine313
        PARENT: alpine
        ISPARENT:  True


      scratch313_3.4.13:
        MAJOR_VERSION: 3
        VERSION:  3.4
        LONG_VERSION: 3.4.13
        VARIANT:  scratch313
        PARENT: scratch
        ISPARENT:  True


      vaapi2204_3.4.13:
        MAJOR_VERSION: 3
        VERSION:  3.4
        LONG_VERSION: 3.4.13
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_3.4.13:
        MAJOR_VERSION: 3
        VERSION:  3.4
        LONG_VERSION: 3.4.13
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True


      ubuntu2204_2.8.22:
        MAJOR_VERSION: 2
        VERSION:  2.8
        LONG_VERSION: 2.8.22
        VARIANT:  ubuntu2204
        PARENT: ubuntu
        ISPARENT:  True


      vaapi2204_2.8.22:
        MAJOR_VERSION: 2
        VERSION:  2.8
        LONG_VERSION: 2.8.22
        VARIANT:  vaapi2204
        PARENT: vaapi
        ISPARENT:  True


      nvidia2204_2.8.22:
        MAJOR_VERSION: 2
        VERSION:  2.8
        LONG_VERSION: 2.8.22
        VARIANT:  nvidia2204
        PARENT: nvidia
        ISPARENT:  True

  steps:
  - template: ../azure-steps.yml
