stages:
  - lint
  - alpine
  - centos
  - nvidia
  - scratch
  - ubuntu
  - vaapi

4.4.1-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.4.1-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.4.1-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

4.4.1-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.4.1-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.4.1-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

4.4.1-vaapi1804:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: vaapi1804
    PARENT: "vaapi"
    ISPARENT: "False"

4.4.1-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.4.1-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4.1"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.3.3-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.3.3-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.3.3-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

4.3.3-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.3.3-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.3.3-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

4.3.3-vaapi1804:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: vaapi1804
    PARENT: "vaapi"
    ISPARENT: "False"

4.3.3-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.3.3-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.3"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.2.5-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.2.5-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.2.5-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

4.2.5-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.2.5-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.2.5-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

4.2.5-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.2.5-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.5"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.1.8-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.1.8-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.1.8-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

4.1.8-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.1.8-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.1.8-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

4.1.8-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.1.8-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.8"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.0.6-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.0.6-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.0.6-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

4.0.6-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.0.6-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.0.6-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

4.0.6-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.0.6-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.4.9-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

3.4.9-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.4.9-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

3.4.9-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

3.4.9-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

3.4.9-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

3.4.9-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

3.4.9-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.9"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.3.9-ubuntu1804:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

3.3.9-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.3.9-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

3.3.9-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

3.3.9-centos8:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

3.3.9-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

3.3.9-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

3.3.9-nvidia2004:
  extends: .docker
  stage: nvidia
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.2.16-ubuntu2004:
  extends: .docker
  stage: ubuntu
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.16"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.2.16-alpine313:
  extends: .docker
  stage: alpine
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.16"
    VARIANT: alpine313
    PARENT: "alpine"
    ISPARENT: "True"

3.2.16-centos7:
  extends: .docker
  stage: centos
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.16"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "True"

3.2.16-scratch313:
  extends: .docker
  stage: scratch
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.16"
    VARIANT: scratch313
    PARENT: "scratch"
    ISPARENT: "True"

3.2.16-vaapi2004:
  extends: .docker
  stage: vaapi
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.16"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"
